/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package examen3ºparcial;

import javax.swing.JFileChooser;
import javax.swing.JOptionPane;

/**
 *
 * @author diegomarquezgomez
 */
public class EXPORTAR extends javax.swing.JFrame {

    /**
     * Creates new form EXPORTAR
     */
    public EXPORTAR() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ARCHIVO = new javax.swing.JTextField();
        SELECCIONA_ARCHIVO = new javax.swing.JButton();
        EXPORTAREXPORTAR = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        SELECCIONA_ARCHIVO.setText("SELECCIONA ARCHIVO");
        SELECCIONA_ARCHIVO.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SELECCIONA_ARCHIVOActionPerformed(evt);
            }
        });

        EXPORTAREXPORTAR.setText("EXPORTAR");
        EXPORTAREXPORTAR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EXPORTAREXPORTARActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(ARCHIVO)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(SELECCIONA_ARCHIVO)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 155, Short.MAX_VALUE)
                .addComponent(EXPORTAREXPORTAR)
                .addGap(152, 152, 152))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ARCHIVO, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(SELECCIONA_ARCHIVO))
                .addGap(18, 18, 18)
                .addComponent(EXPORTAREXPORTAR)
                .addContainerGap(34, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void SELECCIONA_ARCHIVOActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SELECCIONA_ARCHIVOActionPerformed
        JFileChooser archivo=new JFileChooser();
        archivo.setFileSelectionMode(JFileChooser.DIRECTORIES_ONLY);
        
        int se=archivo.showSaveDialog(null);
        if(se==JFileChooser.APPROVE_OPTION){
            String ruta=archivo.getSelectedFile().getPath();
            ARCHIVO.setText(ruta);
        }
        
    }//GEN-LAST:event_SELECCIONA_ARCHIVOActionPerformed

    private void EXPORTAREXPORTARActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EXPORTAREXPORTARActionPerformed
        String ruta=ARCHIVO.getText();
        String nombre="\\Examen3";
        String Examen3="";
        if(ruta.trim().length()!=0){
            try{
                Examen3="mysqldump --opt -u"+CONECTAR.getUsuario()+" -p "+CONECTAR.getContraseña()+" -B "+CONECTAR.getNombre()+" -r "+ruta+nombre;
                Runtime rt=Runtime.getRuntime();
                rt.exec(Examen3);
                JOptionPane.showMessageDialog(null,"Exportacion Correcta");
            }catch(Exception ex){
                JOptionPane.showMessageDialog(null,"No se ha ponido exportar");
            }
        }
    }//GEN-LAST:event_EXPORTAREXPORTARActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EXPORTAR.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EXPORTAR.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EXPORTAR.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EXPORTAR.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new OPCIONES().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField ARCHIVO;
    private javax.swing.JButton EXPORTAREXPORTAR;
    private javax.swing.JButton SELECCIONA_ARCHIVO;
    // End of variables declaration//GEN-END:variables
}
